#pragma once
#define VIAL_KEYBOARD_UID {0x4C, 0xFC, 0xC4, 0x1A, 0x97, 0x78, 0x58, 0x66}
#define VIAL_UNLOCK_COMBO_ROWS { 0, 0 }
#define VIAL_UNLOCK_COMBO_COLS { 0, 5 }
#define VIAL_COMBO_ENTRIES 4
#define VIAL_TAP_DANCE_ENTRIES 4
#define VIAL_KEY_OVERRIDE_ENTRIES 4
